version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grow-habits
